name: build

on:
  pull_request:
  push:

jobs:
  xgo:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        env:
          CGO_ENABLED: "0"
        with:
          dest: build
          targets: windows/amd64,linux/amd64,darwin/amd64
          v: true
          ldflags: -s -w
          buildmode: default
